"""initial_tables

Revision ID: 8a96398b57ef
Revises: 
Create Date: 2025-08-11 16:03:00.513794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a96398b57ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], name=op.f('fk__activities__parent_id__activities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__activities')),
    sa.UniqueConstraint('name', name=op.f('uq__activities__name'))
    )
    op.create_index('ix_activities_name', 'activities', ['name'], unique=False)
    op.create_index('ix_activities_name_parent', 'activities', ['name', 'parent_id'], unique=False)
    op.create_index('ix_activities_parent_id', 'activities', ['parent_id'], unique=False)

    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('house', sa.String(length=10), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__buildings')),
    sa.UniqueConstraint('city', 'street', 'house', name=op.f('uq__buildings__city'))
    )
    op.create_index('ix_buildings_city_postal', 'buildings', ['city', 'postal_code'], unique=False)
    op.create_index('ix_buildings_geo_lat_lon', 'buildings', ['lat', 'lon'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('inn', sa.String(length=10), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('office', sa.String(length=10), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('fk__organizations__building_id__buildings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__organizations')),
    sa.UniqueConstraint('inn', name=op.f('uq__organizations__inn'))
    )
    op.create_index('ix_organizations_building_id', 'organizations', ['building_id'], unique=False)
    op.create_index('ix_organizations_building_office', 'organizations', ['building_id', 'office'], unique=False)
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)

    op.create_table('org_activity',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk__org_activity__activity_id__activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk__org_activity__organization_id__organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id', name=op.f('pk__org_activity'))
    )

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk__phone_numbers__organization_id__organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__phone_numbers')),
    sa.UniqueConstraint('number', name=op.f('uq__phone_numbers__number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    op.drop_table('org_activity')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_index('ix_organizations_building_office', table_name='organizations')
    op.drop_index('ix_organizations_building_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_buildings_geo_lat_lon', table_name='buildings')
    op.drop_index('ix_buildings_city_postal', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_activities_parent_id', table_name='activities')
    op.drop_index('ix_activities_name_parent', table_name='activities')
    op.drop_index('ix_activities_name', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
